openapi: 3.0.0
info:
  title: Tasks
  version: '1.0'
  description: タスクのステータスを取得する
  contact:
    name: cs
servers:
  - url: 'https://api.cs-remote-care.jp/v1'
paths:
  '/tasks/{taskid}':
    parameters:
      - schema:
          type: string
        name: taskid
        in: path
        required: true
        description: タスクID
    get:
      summary: タスクIDでタスク情報を取得する
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  taskid:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - taskid
                  - message
              examples:
                inprogress:
                  value:
                    taskid: '123'
                    message: inprogress
                failed:
                  value:
                    taskid: '123'
                    message: failed
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  taskid:
                    type: string
                  message:
                    type: string
                    minLength: 1
                required:
                  - taskid
                  - message
              examples:
                example-1:
                  value:
                    taskid: ''
                    message: Error for CSRC credentials are incorrect or not authorized.
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  Error:
                    type: string
                    minLength: 1
                required:
                  - Error
              examples:
                example-1:
                  value:
                    Error: Task not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  taskid:
                    type: string
                  message:
                    type: string
                    minLength: 1
                required:
                  - taskid
                  - message
              examples:
                example-1:
                  value:
                    taskid: ''
                    message: Internal Server Error.
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  taskid:
                    type: string
                  message:
                    type: string
                    minLength: 1
                required:
                  - taskid
                  - message
              examples:
                example-1:
                  value:
                    taskid: ''
                    message: Service Unavailable.
      operationId: get-tasks
      description: タスクIDでタスクの状況を確認する
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                auth:
                  type: object
                  properties:
                    applicationid:
                      type: string
                      minLength: 1
                    userid:
                      type: string
                      minLength: 1
                    password:
                      type: string
                      minLength: 1
                  required:
                    - applicationid
                    - userid
                    - password
              required:
                - auth
            examples:
              example-1:
                value:
                  auth:
                    applicationid: JobMgtTool
                    userid: user
                    password: password
        description: 認証情報
components:
  schemas: {}
  securitySchemes: {}
